env:
  name: PSNetwork

name: Run Makefile into $name

on:
  push:
    branches: [ main ]
    paths:
      - '$name/**'
  pull_request:
    branches: [ main ]
    paths:
      - '$name/**'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Swift
      uses: fwal/setup-swift@v1
      with:
        swift-version: '5.9'

    - name: Install dependencies
      run: |
        brew install make

    - name: Run Make
      run: |
        cd $name/
        make all