name: Run Makefile into PSNetwork

env:
  SWIFT_VERSION: 5.9
  PROJECT_NAME: PSNetwork

on:
  push:
    branches: [ main ]
    paths:
      - '$PROJECT_NAME/**'
  pull_request:
    branches: [ main ]
    paths:
      - '$PROJECT_NAME/**'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Swift
      uses: fwal/setup-swift@v1
      with:
        swift-version: '$SWIFT_VERSION'

    - name: Install dependencies
      run: |
        brew install make

    - name: Run Make
      run: |
        cd $PROJECT_NAME/
        make all
